use_frameworks!

target 'VehicleModelSelector_Example' do
  pod 'VehicleModelSelector', :path => '../'

  target 'VehicleModelSelector_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end
